# Welcome to Mago!
# For full documentation, see https://mago.carthage.software/tools/overview
php-version = "8.2.0"

[source]
workspace = "."
paths = ["app/", "database/factories/", "database/seeders/", "tests/"]
includes = ["vendor"]
excludes = []

[formatter]
print-width = 120
tab-width = 4
use-tabs = false

[linter]
integrations = ["laravel"]

[linter.rules]
ambiguous-function-call = { enabled = false }
literal-named-argument = { enabled = false }
halstead = { effort-threshold = 7000 }

[analyzer]
find-unused-definitions = true
find-unused-expressions = true
analyze-dead-code = true
memoize-properties = true
allow-possibly-undefined-array-keys = false
check-throws = true
check-missing-override = true
find-unused-parameters = true
strict-list-index-checks = false
no-boolean-literal-comparison = true
check-missing-type-hints = true
register-super-globals = true